### ISSUE TITLE
[Bug] Disable Thorn Cylinders code also affect one of the Koco challenges on Kronos

### ISSUE THREAD

**Issue by Optimus-Bull** [hedge-dev/HMMCodes#63] opened 2023-11-19 17:37 UTC
The code "Disable Thorn Cylinders" which is supposed to remove the thorn cylinders that are placed in inconvenient locations in Cyber Space also affects one of the Koco challenges that is on Kronos Island.

The one near Big's fishing portal where you have to quick step on platforms in order to get one of the bigger Kocos that increase the Boost Gauge.

Turning it off does resolves this, though the code should ideally only affect the thorn cylinders in Cyber Space and not in the Open Zones. At least not affect that particular Koco challenge as it renders too easy and trivial compared to other challenges.

**Comment by HyperBE32** [comment] 2023-11-19 17:39
I've updated the code to remove the note about Cyber Space from the description.

It was organised into `Gameplay/Objects` when subcategories were introduced and I forgot about it.

This code is functioning as intended, there are no plans to change its behaviour.

Closing...

**Closed by HyperBE32** 2023-11-19 17:39 UTC
Labels: wontfix

**Comment by Optimus-Bull** [comment] 2023-11-19 19:37
Oh it's supposed to do this to Thorn Cylinders in the Open Zone too?
Didn't know that. My mistake. Thanks for clarifying. :)
