### ISSUE TITLE
[SonicOrigins] 

### ISSUE THREAD

**Issue by AnnaUekawa** [hedge-dev/HMMCodes#69] opened 2023-11-22 06:31 UTC
[HMM_Snapshot_00112023003055.txt](https://github.com/hedge-dev/HMMCodes/files/13434454/HMM_Snapshot_00112023003055.txt)

HMM Info:
```
    Version: 7.12-3
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicOrigins\build\main\projects\exec
    Process Level: User
    Game: Sonic Origins
    GameInstall: Sonic Origins
    Update Status: Up To Date
```

Exception:
```
    Message: Error Compiling Codes
    - Sonic Origins Ultrafix\UltrafixHEPatches
        Error @(2,25) CS0103: The name 'Reflection' does not exist in the current context
        Error @(6,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(6,34) CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
        Error @(7,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(7,34) CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
        Error @(8,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(8,34) CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
        Error @(9,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(9,34) CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
        Error @(10,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(10,34) CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
        Error @(11,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(11,34) CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
        Error @(12,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(12,34) CS0103: The name 'm_RetroSfxSonic1' does not exist in the current context
        Error @(13,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(13,34) CS0103: The name 'm_RetroSfxSonic1' does not exist in the current context
        Error @(14,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(14,34) CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
        Error @(15,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(15,34) CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
        Error @(16,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(16,34) CS0103: The name 'm_RetroSfxSonic3k' does not exist in the current context
        Error @(17,1) CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
        Error @(17,34) CS0103: The name 'm_RetroSfxSonic3k' does not exist in the current context


```

**Comment by ActualMandM** [comment] 2023-11-22 06:31
This issue was caused by a mod and not by a code from this repository.

As a quick troubleshoot, make sure your codes are up to date by going to the Codes tab and clicking Download/Update Community Codes.
If this issue still persists after that, then contact the author(s) of the mod.

Closing.

**Closed by ActualMandM** 2023-11-22 06:31 UTC
