### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by ExcelionWolf** [hedge-dev/HMMCodes#167] opened 2024-10-26 15:29 UTC
im getting this error now whenever i try to open the game with HMM and i am not even using the codes
HMM Info:
```
    Version: 7.13-1-4ff06ee
    Args: 
    StartDir: C:\Users\matia\Downloads\HedgeModManager\
    Process Level: User
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Message: Error Compiling Codes
    - Plugins
        Warning @(6,114) CS0105: The using directive for 'Collections' appeared previously in this namespace

    - Fix Recovery Jump Transitions
        Error @(25,38) CS0103: The name 'DeltaTime' does not exist in the current context
        Error @(42,38) CS0103: The name 'DeltaTime' does not exist in the current context


```

**Comment by ActualMandM** [comment] 2024-10-26 19:17
This issue was caused by a mod and not by a code from this repository.

As a quick troubleshoot, make sure your codes are up to date by going to the Codes tab and clicking Download/Update Community Codes.

If this issue still persists after that, then contact the author(s) of the mod.

**Comment by ActualMandM** [comment] 2024-10-26 19:20
Thought it was a mod causing the issue, apologies

**Comment by hyperbx** [comment] 2024-10-26 21:55
This should be fixed as of commit https://github.com/hedge-dev/HMMCodes/commit/b69e69a7d307371ae773cd1f376c870c080431d5, download the latest community codes via the Codes tab and try again.

**Comment by ExcelionWolf** [comment] 2024-10-26 22:00
solved it doing that

**Closed** 2024-10-26 22:01 UTC
Labels: bug
