### ISSUE TITLE
[Sonic Frontiers] Always Dodge with Side Step does not allow for parrying whilst grounded

### ISSUE THREAD

**Issue by Icedude907** [hedge-dev/HMMCodes#47] opened 2023-11-04 11:18 UTC
Jumps to the dodging state without waiting for the parry window

Presumably caused by this:
https://github.com/hedge-dev/HMMCodes/blob/ce2fc2708bc065c8da2e0b3e489e1f5ff553a846/Source/Sonic%20Frontiers/Gameplay/Always%20Dodge%20with%20Side%20Step.hmm#L50

**Comment by HyperBE32** [comment] 2023-11-04 11:43
That is the cause, yes. I plan to bring back a mid-asm hook I wrote to achieve this, as I realised getting parry to work again would require a complete reimplementation, much like what I already had to do to get it to work in Cyber Space without hacking the game code to bits to even allow it.

**Comment by HyperBE32** [comment] 2023-11-05 06:47
Fixed in commit https://github.com/hedge-dev/HMMCodes/commit/f4b75badb6e3941c08f425acbb5efa4f556bea2e.

**Closed by HyperBE32** 2023-11-05 06:47 UTC
Labels: bug
